server:
  servlet:
    contextPath: /api/dev
  port: 9090
  error:
    include-stacktrace: NEVER
---
spring:
  application: customer-registration-service
    name: 
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/grocery_customer_registration-service
    username: root
    password: root
---          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost
